### ISSUE TITLE
Hackbar can't execute post data correctly

### ISSUE THREAD

**Issue by lzskyline** [khoiasd/hackbar#6]
When I check "Post Data" and click "Execute", nothing happened.
I have to uncheck "Post Data" and Execute get method once, then re-check "Post Data" to solve this problem temporarily, that means I have to switch checkbox status and execute every time when I want to use Post method.
I don't know if it's my problem, someone has the same bug?

Firefox 57 Quantum

====================
New Problem:

I upgraded my firefox just now, It's Firefox 58.0.1, then my hackbar can't load.
When I press F12 and switch hackbar tab, It tips 404 and says "Can't find the file: moz-extension://e8713e8c-3f2e-4367-80ee-9e68523a4b5e/theme/theme/hackbar-panel.html"

**Comment by HongLuDianXue** [comment]
Me too.

**Comment by lzskyline** [comment]
I just reinstalled this plugin and found that the bug has been fixed.

**Comment by SleepProgger** [comment]
I still have this problem after i once got a 200 response in Firefox 60.2.1esr (64-bit)

First post request: works
If the response status is != 200 each click on execute properly sends another request.
But as soon as the response status is == 200 following clicks on execute do nothing.

The workaround described by lzskyline works (sending get request (which in my case leads to a status != 200)) and after that i can send one more post request.
If required i could provide an example.
